### ISSUE TITLE
Mocking Camera for QR-scanner

### ISSUE THREAD

**Issue by amnonjw** [stonelasley/ionic-mocks#13]
Hello,
I want to create a unit test for QR scanner, for an ionic Android app. Since it requires a camera I was thinking of using this ionic-native-mocks plugin.
However, from ionic-native/barcode-scanner I can only use the scan() method which automatically opens a camera on an Android emulator.

So my questions are:

- Does using the ionic-native-mocks eliminates the requirement for an emulator to start the native interface for the barcode-scanner?

- I currently use Jasmine and Karama for running unit tests. Do I need end-to-end testing like Protractor if I want to use ionic-native-mocks?

- The barcode-scanner can chose between a front and a back camera, but I don't know how to tell him to use a mock camera, unless I somehow register the ionic-native-mocks/camera as a front camera. Would I still need to run this on an emulator?

**Comment by amnonjw** [comment]
oops, wrong discussion board.

**Comment by stonelasley** [comment]
@amnonjw I can probably answer the questions for you. 

- You won't need an emulator a mock is just a stand-in and provides no real functionality
- No you won't need end to end, mocks are better suited to very focused unit tests done in isolation.
- Your mock is really just allowing your component to make calls on a "dumb" object, there shouldn't be any camera interaction.
