### ISSUE TITLE
Problem with ion-slides

### ISSUE THREAD

**Issue by baart1989** [stonelasley/ionic-mocks#15]
I have encountered similiar error which was previously reported under following project: https://github.com/lathonez/clicker/issues/227.

Uncaught TypeError: this._plt.timeout is not a function
Which is because we don't mock timeout in platformmock.

This is [commit](https://github.com/lathonez/clicker/commit/d7ee4d43df334545e8e600dab8f67caccb9c2944) which has fixed it.

Can we add it to fix the above error ?

**Comment by stonelasley** [comment]
@baart1989 would you mind testing the changes I made to platform on branch platform-updates

https://github.com/stonelasley/ionic-mocks/commit/02fbada20c18662ce6dd6010913434a995456573

**Comment by baart1989** [comment]
Hello @stonelasley, unfourtunately my tests containing slides component are still not working with your latest changes.

Now I am getting following error TypeError: plt.resize.subscribe is not a function.
This is thrown because of setTimeout(callback, timer);

Changing and.callFake to .and.returnValue seems to be resolving it.

**Comment by stonelasley** [comment]
@baart1989 I just pushed an update to this branch if you wouldn't mind testing it again I'd really appreciate it. Been slammed with work this week so I haven't been able to do much.

**Comment by baart1989** [comment]
Thanks @stonelasley. It works fine for me now.

**Comment by stonelasley** [comment]
@euleule @baart1989, thank you, both for your help. I just published v0.13.0 that should address the platform issues.
