### ISSUE TITLE
Add setRoot to NavControllerMock

### ISSUE THREAD

**Issue by calumsult** [stonelasley/ionic-mocks#18]
The nav controller mock is missing setRoot, can that be added? Treat it just like push or pop?

**Comment by stonelasley** [comment]
@calumsult thanks for raising this issue. I can add that.

**Comment by stonelasley** [comment]
@calumsult this should be ready to go in the latest version. 1.0.2

**Comment by calumsult** [comment]
Thanks!

**Comment by Abhishek-Kanitkar** [comment]
Is this commit by @calumsult merged into master branch ?

I am still getting setRoot not available as error when I try to use NavControllerMock into my unit tests.
