### ISSUE TITLE
ModalControllerMock missing property 'create'

### ISSUE THREAD

**Issue by BenjaminKauer** [stonelasley/ionic-mocks#24]
~~Recently installed 1.0.1. Getting a `TypeError: Cannot read property 'create' of undefined` since modal-controller.d.ts indeed has no property 'create':~~

~~In version 0.13.0 the ModalControllerMock still worked as expected.~~

**Update:**
I just re-installed v0.13.0 and it still doesn't work, so something else causes the error, obviously. This issue may be closed.

**Comment by stonelasley** [comment]
@BenjaminKauer Thanks for the issue, if you need further help feel free to ping me.
