### ISSUE TITLE
modalCtrl onDidDismiss

### ISSUE THREAD

**Issue by Remco75** [stonelasley/ionic-mocks#30]
There is a something implemented for onDisDismiss on the modalCtrlMock.
But as far a I could figure out there is no callback method implemented. I would like to test wheter the code executed on dismiss gets called and does what it's supposed to. Am I missing something here?

**Comment by enstain** [comment]
This is an open PR yet: https://github.com/stonelasley/ionic-mocks/pull/26

**Comment by Remco75** [comment]
aaah, sorry forgot to check! thnx

**Comment by stonelasley** [comment]
@Remco75 this should be included in latest version. Thanks for opening the issue, and thanks again @enstain for the PR.
