### ISSUE TITLE
onDisdismiss does not carry arguments

### ISSUE THREAD

**Issue by Remco75** [stonelasley/ionic-mocks#32]
The onDidDismiss functionality introduced in PR #26 does indeed call the callback, but without the arguments ( I think, thats one of the things you want tested actually)

Should be a fairly easy fix, I will try to create a PR this week if you want (or you can implement it yourself of course ;-)

**Comment by Remco75** [comment]
ok, I just went balls to the walls and just created the PR ;-)

**Comment by stonelasley** [comment]
v1.2.1 thank you!
