### ISSUE TITLE
Add ionViewCanEnter and ionViewCanLeave to NavControllerMock

### ISSUE THREAD

**Issue by racedale** [stonelasley/ionic-mocks#34]
Is it possible to add these? I'm trying to figure out how to add tests that these were called correctly

**Comment by stonelasley** [comment]
@racedale I think @enstain is right, this is complex and these mocks will likely need to be tailored to your specific needs. But remember, even if these mocks don't provide what you need out of the box (which they shouldn't be expected to) you can add onto them so they meet your current use case. 
```typescript
..test setup

beforeEach(() => {
    let mock = AnyMock.instance();
    mock.ionViewCanEnter.and.returnValue(false); //or whatever else you need it to be and you may need to mock it differently in a couple different test cases.
    ...
})
