### ISSUE TITLE
_dismissCallback is not a function

### ISSUE THREAD

**Issue by AlexandreDenis** [stonelasley/ionic-mocks#40]
I don't know if it is a bug or a misuse but I am developing test for my Ionic application and I tried to use your `AlertControllerMock` and `AlertMock` classes.
So I configure my `TestBed` to inject the mocks instead of the Ionic classes like you describe in the `README.md` file (using `useFactory` in the providers of my module).
Every thing seemed to work fine until I tried to call the `dismiss()` method of an `AlertMock` instance. As far as I know, this is how we programmatically close an Ionic `Alert`.
But with the `AlertMock` instance, an exception is raised saying that `_dismissCallback is not a function`.

Is it a bug or a misuse?

**Comment by stonelasley** [comment]
@AlexandreDenis sorry for the delay in response, been a bit busy with other projects. If you're interested I'd love for you to see if branch Issue20-dismisscallback fixes the issue for you.

**Comment by stonelasley** [comment]
@AlexandreDenis v1.2.1 should fix this.

**Comment by AlexandreDenis** [comment]
@stonelasley It did. I fix the issue this way on my project. Thanks for your work !
