### ISSUE TITLE
Ionic Linting Issues?

### ISSUE THREAD

**Issue by lathonez** [stonelasley/ionic-mocks#5]
Hey,

When I run this with Clicker, I get a ton of linting errors from:

```
ionic-app-scripts lint
```

Have you applied some config to your ionic projects to get around this?

I'm unsure why it's throwing linting errors from ionic-mocks and nothing else. Seems similar enough to this: https://stackoverflow.com/questions/42483922/exclude-node-modules-from-tslint-in-ionic-2-app

What do you think?

**Comment by lathonez** [comment]
FYI I've stopped Ionic from linting and am now running my own linting command instead. You may find this is an issue for others using this module with vanilla Ionic though!

Cheers

**Comment by stonelasley** [comment]
@lathonez sorry about that, I didn't notice any linting errors as I was adding it to clicker (I think). I'll look into this ASAP though in the context of clicker.  https://github.com/UintaGroup/axpense is also using ionic-mocks and I linted that whole project last week and am pretty sure I'd have run into it. Either way, I probably should add some linting rules to this project and clean it up a bit more.

**Comment by stonelasley** [comment]
I'm able to reproduce this. I should have an update out this weekend.

**Comment by stonelasley** [comment]
should be good now, linted against tslint-ionic-rules. 
https://github.com/stonelasley/ionic-mocks/commit/b6386344efb2cbaf2fdca718b9a64173e44c86ad
